export const posts = [
	{
		title: 'Test Post',
		message: 'Very Small text',
		name: 'Creator 1',
		creator: 'String2',
		tags: ['String'],
		_private: false,
		selectedFile: 'https://cdn.kimkim.com/files/a/content_articles/featured_photos/0e3794a0b646d638627afb626bf9ee46f472feb1/big-0bb2a2bea537c680f141d40cb484d888.jpg',
		likes: ['61dbfb880fa65a2cef044ef7'],
		comments: ['as: asdasd', 'sd: asdasd'],
		createdAt: new Date(),
		_id: 1,
	},
	{
		title: 'Test Post 2',
		message:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
		name: 'John Doe',
		creator: 'String',
		tags: ['String', 'sdasd', 'sdasd', 'asdasdasd', 'asdasdsad', 'ssada'],
		_private: true,
		selectedFile: 'https://www.anirbansaha.com/wp-content/uploads/2018/07/kolkata_gate_001.jpg',
		likes: ['12222', '2123', 'Pritam'],
		comments: ['as: asdasd', 'sd: asdasd'],
		createdAt: '2019-01-15T19:54:11.737+00:00',
		_id: 2,
	},
	{
		title: 'Eyes Blue',
		message: 'Just a sentence',
		name: 'Jane Doe Big Name',
		creator: 'String',
		tags: ['String', 'sdasd', 'sdasd', 'asdasdasd', 'asdasdsad', 'ssada'],
		_private: true,
		selectedFile: 'https://i.ytimg.com/vi/xDFwqJ4F50U/maxresdefault.jpg',
		likes: ['12222', '2123', '61dbfb880fa65a2cef044ef7', '61dc0adf479a28eefc306603'],
		comments: ['as: asdasd', 'sd: asdasd'],
		createdAt: '2022-01-15T19:54:11.737+00:00',
		_id: 3,
	},
	{
		title: 'Test Post 2',
		message:
			"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
		name: 'Jane Doe',
		creator: '1123123xcxsew23',
		tags: ['String', 'sdasd', 'sdasd', 'asdasdasd', 'asdasdsad', 'ssada'],
		_private: true,
		selectedFile: 'https://www.croatiaweek.com/wp-content/uploads/2021/10/croatia-best-destination.jpg',
		likes: ['12222', '2123'],
		comments: ['as: asdasd', 'sd: asdasd'],
		createdAt: '2022-06-15T19:54:11.737+00:00',
		_id: 4,
	},
	{
		title: 'Test Post 2',
		message: 'This sis a test message // const { posts, isLoading } = useSelector(state => state.posts) /xcxzcxcvxcvxsfa  qwerq3we23 wer34 35/ [] -> { isLoading, posts: [] }',
		name: 'Jane Doe',
		creator: 'String',
		tags: ['String', 'sdasd', 'sdasd', 'asdasdasd', 'asdasdsad', 'ssada'],
		_private: false,
		selectedFile: 'https://assets.vogue.in/photos/6239a88deb60bae3c5bc6821/2:3/w_2560%2Cc_limit/Dubai.jpg',
		likes: ['12222', '2123', '61dc0adf479a28eefc306603'],
		comments: ['as: asdasd', 'sd: asdasd'],
		createdAt: new Date(),
		_id: 5,
	},
	{
		title: 'Test Post 2',
		message: 'This sis a test message // const { posts, isLoading } = useSelector(state => state.posts) /xcxzcxcvxcvxsfa  qwerq3we23 wer34 35/ [] -> { isLoading, posts: [] }',
		name: 'Jane Doe',
		creator: 'String',
		tags: ['String', 'sdasd', 'sdasd', 'asdasdasd', 'asdasdsad', 'ssada'],
		_private: true,
		selectedFile: 'https://assets.vogue.in/photos/6239a88deb60bae3c5bc6821/2:3/w_2560%2Cc_limit/Dubai.jpg',
		likes: ['12222', '2123'],
		comments: ['as: asdasd', 'sd: asdasd'],
		createdAt: new Date(),
		_id: 6,
	},
	{
		title: 'Test Post 2',
		message: 'This sis a test message // const { posts, isLoading } = useSelector(state => state.posts) /xcxzcxcvxcvxsfa  qwerq3we23 wer34 35/ [] -> { isLoading, posts: [] }',
		name: 'Jane Doe',
		creator: 'String',
		tags: ['String', 'sdasd', 'sdasd', 'asdasdasd', 'asdasdsad', 'ssada'],
		_private: true,
		selectedFile: 'https://www.remax.eu/uploads/agent-1/9%20Switzerland-(Optimized)1.jpg',
		likes: ['12222', '2123'],
		comments: ['as: asdasd', 'sd: asdasd'],
		createdAt: new Date(),
		_id: 7,
	},
	{
		title: 'Test Post 2',
		message: 'This sis a test message // const { posts, isLoading } = useSelector(state => state.posts) /xcxzcxcvxcvxsfa  qwerq3we23 wer34 35/ [] -> { isLoading, posts: [] }',
		name: 'Jane Doe',
		creator: 'String',
		tags: ['String', 'sdasd', 'sdasd', 'asdasdasd', 'asdasdsad', 'ssada'],
		_private: false,
		selectedFile: 'https://i.pinimg.com/236x/bd/7d/37/bd7d37afd91aa9f7b103907c6d1527f0.jpg',
		likes: ['12222', '2123'],
		comments: ['as: asdasd', 'sd: asdasd'],
		createdAt: new Date(),
		_id: 8,
	},
	{
		title: 'Lovers',
		message: 'This sis a test message // const { posts, isLoading } = useSelector(state => state.posts) /xcxzcxcvxcvxsfa  qwerq3we23 wer34 35/ [] -> { isLoading, posts: [] }',
		name: 'Jane Doe',
		creator: 'String',
		tags: ['String', 'sdasd', 'sdasd', 'asdasdasd', 'asdasdsad', 'ssada'],
		_private: false,
		selectedFile: 'https://i.pinimg.com/236x/bd/7d/37/bd7d37afd91aa9f7b103907c6d1527f0.jpg',
		likes: ['12222', '2123'],
		comments: ['as: asdasd', 'sd: asdasd'],
		createdAt: new Date(),
		_id: 7,
	},
	{
		title: 'Test Post 4',
		message: 'This sis a test message // const { posts, isLoading } = useSelector(state => state.posts) /xcxzcxcvxcvxsfa  qwerq3we23 wer34 35/ [] -> { isLoading, posts: [] }',
		name: 'Jane Doe',
		creator: 'String',
		tags: ['String', 'sdasd', 'sdasd', 'asdasdasd', 'asdasdsad', 'ssada', 'String', 'asdasdsad', 'ssada', 'String'],
		_private: false,
		selectedFile: 'https://assets.vogue.in/photos/6239a88deb60bae3c5bc6821/2:3/w_2560%2Cc_limit/Dubai.jpg',
		likes: ['12222', '2123'],
		comments: ['as: asdasd', 'sd: asdasd'],
		createdAt: new Date(),
		_id: 8,
	},
]
