export { default as CreateComment } from './CreateComment'
export { default as CreatePost } from './CreatePost'
export { default as ForgotPassword } from './ForgotPassword'
export { default as LogIn } from './LogIn'
export { default as ResetPassword } from './ResetPassword'
export { default as Search } from './Search'
export { default as SignUp } from './SignUp'
export { default as UpdateProfile } from './UpdateProfile'
